apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-ui-nginx-conf
  namespace: ks-shop-flashsale
  labels:
    app: nginx-conf
data:
  nginx.conf: |
    server {
        listen  80;
        server_name shop-ui;

        location / {
            root /usr/share/nginx/html/;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root    html;
        }
    }
