apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cimp-web
    component: web
    tier: frontend
  name: cimp-web
  namespace: miyu
spec:
  progressDeadlineSeconds: 600
  replicas: REPLICAS
  selector:
    matchLabels:
      app: cimp-web
      component: web
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cimp-web
        component: web
        tier: frontend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: cimp-web
          image: REGISTRY/DOCKERHUB_NAMESPACE/APP_NAME:SNAPSHOT-BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-conf
          configMap:
            name: cimp-web-nginx-conf
            items:
            - key: nginx.conf
              path: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
