apiVersion: v1
kind: Service
metadata:
  labels:
    app: cimp-web
    component: web
  name: cimp-web
  namespace: miyu
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: cimp-web
    component: web
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.2.230
